M48
; DRILL file {KiCad (7.0.0)} date Tue 14 Mar 2023 10:36:46 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-14T22:36:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X0.0575Y-0.4724
X0.0575Y-0.5724
T2
X2.5197Y-0.563
X2.5197Y-1.0118
T0
M30
