M48
; DRILL file {KiCad 9.0.5} date 2025-10-08T15:34:29+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-08T15:34:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X57.15Y-99.7
X65.15Y-99.7
T2
X112.1Y-31.5
X112.1Y-98.5
T3
X109.9Y-41.8
X109.9Y-53.2
M30
